Document: pig-latin
Title: Debian pig-latin Manual
Author: <insert document author here>
Abstract: This manual describes what pig-latin is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/pig-latin/pig-latin.sgml.gz

Format: postscript
Files: /usr/share/doc/pig-latin/pig-latin.ps.gz

Format: text
Files: /usr/share/doc/pig-latin/pig-latin.text.gz

Format: HTML
Index: /usr/share/doc/pig-latin/html/index.html
Files: /usr/share/doc/pig-latin/html/*.html
